theme: jekyll-theme-hacker
title: CATS (Constructing Algorithmic Trading Structures)
description: An introduction to data collection, processing, and model prediction using market book data (both level 1 and level 2 data)
